# Generated by Django 4.1.3 on 2022-11-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profesor_delete_person_alter_cliente_descuento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen_Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_fecha', models.DateField(auto_now=True)),
                ('curso', models.CharField(max_length=30)),
                ('evaluador', models.CharField(max_length=50)),
                ('duracion_examen', models.DateField(auto_now=True)),
                ('n_preguntas', models.IntegerField(default=0)),
                ('puntaje_total', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_fecha', models.DateField(auto_now=True)),
                ('curso', models.CharField(max_length=30)),
                ('evaluador', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=100)),
                ('n_grupos', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='examen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nota_laboratorio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profesor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profesor',
            name='salario',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ProyectoProxy',
            fields=[
            ],
            options={
                'ordering': ['tema'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.proyecto',),
        ),
    ]
