# Generated by Django 4.1.3 on 2022-12-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_examen_final_proyecto_alumno_examen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=100)),
                ('average_rating', models.CharField(max_length=10)),
                ('isbn', models.CharField(max_length=20)),
                ('isbn13', models.CharField(max_length=20)),
                ('language_code', models.CharField(max_length=10)),
                ('num_pages', models.CharField(max_length=10)),
                ('ratings_count', models.IntegerField()),
                ('text_reviews_count', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=20)),
            ],
        ),
    ]
