# Generated by Django 4.1.3 on 2022-12-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_libro_authors_alter_libro_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='authors',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='libro',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='publisher',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='libro',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
